default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tuesdays-with-toni-app_development

test:
  <<: *default
  database: tuesdays-with-toni-app_test

production:
  <<: *default
  database: tuesdays-with-toni-app_production
  username: tuesdays-with-toni-app
  password: <%= ENV['TUESDAYS-WITH-TONI-APP_DATABASE_PASSWORD'] %>
