# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73282823be00e8ab2f4ae9c8b426a5ab34ee44661ef318268df46afc6c60d07a1a6193a0ac11ed8c5ebda5e14f44e4529fa707bb6fcb98527d92638c5f0438af

test:
  secret_key_base: e8b123c13e29a9c056f1f4781fc00d81143e96f9a359a326d1e18d5d1a359faf29da9bf7ae82610b7e36e2f2db9ed89e4c02546c924779d771e230f785250696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
